name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'

    - name: Build
      run: |
        chmod +x gradlew
        ./gradlew build

    - uses: actions/upload-artifact@v2
      with:
        path: build/libs

